name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_USER: product_user
          MYSQL_PASSWORD: product_user_password
          MYSQL_DATABASE: product
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if docker exec mysql mysqladmin ping --silent &> /dev/null; then
            break
          fi
          echo 'MySQL is unavailable - sleeping'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not become available in time' >&2
          exit 1
        fi

    - name: Build with Maven
      run: mvn -f backend/pom.xml clean install -e
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/product
        SPRING_DATASOURCE_USERNAME: product_user
        SPRING_DATASOURCE_PASSWORD: product_user_password

    - name: Run Tests
      run: mvn -f backend/pom.xml test -e
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/product
        SPRING_DATASOURCE_USERNAME: product_user
        SPRING_DATASOURCE_PASSWORD: product_user_password

    - name: Build Docker Image
      run: docker build -t your-dockerhub-username/backend:latest ./backend

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push your-dockerhub-username/backend:latest